name: Audit de Sécurité Cloud

on:
  push:
    branches: [ "main" ]

jobs:
  prowler-scan:
    runs-on: ubuntu-latest
    name: Scan AWS avec Prowler
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Installation de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installation de Prowler
        run: pip install prowler

      - name: Lancement du Scan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        # On lance Prowler pour scanner spécifiquement la faille SSH (port 22 ouvert)
        run: prowler aws --checks ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22 --region us-east-1 --no-banner